name: Build Extension

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install web-ext
        run: npm install -g web-ext
        
      - name: Build extension
        run: web-ext build --overwrite-dest
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts/ 