name: Build Extension

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git tags
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
          
      - name: Get version from git
        id: get_version
        run: |
          # If this is a tag, use it (without 'v' prefix)
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # Otherwise use latest tag + commit hash
            VERSION=$(git describe --tags --always --dirty | sed 's/^v//')
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
      - name: Build extensions
        run: npm run build
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: web-ext-artifacts/firefox/*-firefox.zip
          
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: web-ext-artifacts/chrome/*-chrome.zip 