name: Release to Firefox Add-ons

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml  # Reuse the build workflow

  release:
    needs: build  # Wait for build to complete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install web-ext
        run: npm install -g web-ext
        
      - name: Sign extension
        run: |
          web-ext sign \
            --api-key=${{ secrets.AMO_JWT_ISSUER }} \
            --api-secret=${{ secrets.AMO_JWT_SECRET }} \
            --channel=listed \
            --amo-metadata=manifest.json
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: web-ext-artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 